[package]
name = "street-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
serde.workspace = true
toml.workspace = true
uuid.workspace = true
